spring.application.name=Employee_Management_System
spring.datasource.url=jdbc:mysql://localhost:3306/emp
spring.datasource.username=root
spring.datasource.password=Rakesh123.ink
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true